DROP DATABASE IF EXISTS ohlcv;
CREATE DATABASE ohlcv;
DROP USER ohlcv@LOCALHOST;
CREATE USER ohlcv@LOCALHOST IDENTIFIED BY 'ohlcv';
GRANT ALL PRIVILEGES ON ohlcv.* TO 'ohlcv'@'localhost';
FLUSH PRIVILEGES;
USE ohlcv;
DROP SCHEMA IF EXISTS ohlcv;
CREATE SCHEMA ohlcv DEFAULT CHARACTER SET UTF8MB4;

